### ISSUE TITLE
next_tickの間隔について

### ISSUE THREAD

**Issue by JunyaW** [unageanu/jiji2#416]
素晴らしいシステムトレードフレームワーク、ありがとうございます。
初心者なのですが質問がございます。

next_tickの行われる間隔を15秒からより長い時間に変更することはできるのでしょうか？

**Comment by unageanu** [comment]
環境変数 `TICK_INTERVAL` を指定することで変更可能です。
`docker-compose.yml` に以下の設定を追加して再起動してみてください。

```
jiji:
  container_name: jiji_jiji
  image: unageanu/jiji:latest
  links:
    - mongodb
  environment:
    USER_SECRET: (略)
    TICK_INTERVAL: 60  # ←間隔を秒で指定
(略)
```
